### PR TITLE
Add a props to change the main tag

### PR DESCRIPTION
**Pull request by lionel-bijaoui**
#197

### CODE REVIEW

**Comment by icebob** [comment]
Great! But please add relevant test too.

**Comment by lionel-bijaoui** [comment]
@icebob I don't really know what to test... `is` is a vuejs feature and I don't know where to begin here. Can you give me a hand ?

**Comment by icebob** [comment]
We [here](https://github.com/icebob/vue-form-generator/blob/master/test/unit/specs/VueFormGenerator.spec.js#L46) test the root element is a "fieldset". Clone it, set the `tag` prop and check the result :) Thanks!

**Comment by lionel-bijaoui** [comment]
Oh ok ! I feared I needed to test everything, what a relief 😅 
I do it right now ! Thanks !

**Comment by lionel-bijaoui** [comment]
@icebob I have beefed up the props with a simple validator. If you feed `tag` with an empty value, it will fail visibly.
Good to merge ?

**Pull request merged**
