### PR TITLE
Grouping fields

### PR DESCRIPTION
**Pull request by icebob**
This PR add two new features to vfg by @dflock & @jmverges.
1. add ID prefix for fields
2. support to grouping fields of schema
Syntax:
```js
schema: {
    groups:[{
        legend: "Contact Details",
        fields: [
            {
                type: "input",
                inputType: "text",
                label: "Name",
                model: "name"
            },
            {
                type: "input",
                inputType: "email",
                label: "Email",
                model: "email"
            }
        ]
    },{
        legend: "Other Details",
        fields: [
            {
                type: "input",
                inputType: "text",
                label: "More",
                model: "others.more"
            },
            {
                type: "input",
                inputType: "text",
                label: "Things",
                model: "others.things"
            }
        ]
    }],
    fields: [
        {
            type: "input",
            inputType: "text",
            label: "Single field (without group)",
            model: "single"
        }
    ]
}
```

Dev example: http://localhost:8080/grouping/

### CODE REVIEW

**Comment by jmverges** [comment]
@icebob what I try to explain before is:
```
       mounted(){
            let $this = this;
            this.$watch('model', function () {
                let prop = {};
                clearTimeout($this.timer);
                $this.timer = setTimeout(function () {
                    $this.build();
                    $this.schema = {groups:$this.getSheets()};
                }, 1000);
            }, {deep: true});
            this.build();
            this.schema =  {groups:$this.getSheets()};
        },
```

I'm recreating the schema each time the model changes as the schema has linked <select> between them. Each time I update schema, a weird behaviour happen.
First:
image
Then I select a VehicleType
image

**Comment by icebob** [comment]
@jmverges Could you create a jsfiddle?

**Comment by icebob** [comment]
@dflock In https://github.com/icebob/vue-form-generator/pull/209/commits/d00886911473cb305910411455a34f6ebb155f2d a made simpler solution for `fieldIdPrefix`. Could you check it?

**Comment by icebob** [comment]
Further tasks before merge:
- [ ] fix tests
- [ ] cover with tests the new features
- [ ] update docs

Somebody can help? At least with docs :)

**Comment by dflock** [comment]
This looks good.

I'd still advocate calling it `schema.fieldsets` instead of `schema.groups` - because that automatically tells you what the feature does and what output you're going to get.

**Comment by jmverges** [comment]
I would like to have that somehow configurable, or "hackable" somehow. Think about doing some tabs for each "fieldset" you may need to change the group rendering.

**Comment by icebob** [comment]
I think `groups` it's not bad. More simpler than `fieldset`. And we need to add it to docs, how it's working

**Comment by icebob** [comment]
In the future we can add `tag` to groups too and we can create not just `<fieldset>` -> `<legend>`, but even `<section>`->`<header>`.

**Comment by dflock** [comment]
Ok, calling it groups is fine.

I think if I was doing multiple tabs, I'd probably do the tab markup outside of vfg and have multiple calls to vfg, one per tab, maybe? Haven't thought about it too deeply. What about multiple tabs, with groups/fieldsets on each tab? I think the groups thing should just do fieldsets - don't try and make it do everything.

**Comment by dflock** [comment]
I'll start updating the docs now.

**Comment by icebob** [comment]
Thanks @dflock. Test fixed.

**Comment by icebob** [comment]
> Just my thougths: In the future maybe would be good a `visible` property in groups (like in fields). Would be easy to turn on/off the whole group.

**Comment by dflock** [comment]
OK, docs changes are done (I think), here: https://www.gitbook.com/book/icebob/vueformgenerator/changes/7

**Comment by jmverges** [comment]
Good morning guys,

A lot of work you did! 

@icebob removing "sync" removes the possibility to update the schema and get the form rebuild. did you try it?

Cheers

**Comment by icebob** [comment]
@dflock Thank you. I'm checking...

@jmverges I removed sync because it is not neccessary. It is sticked in from Vue 1.x. Because vfg stored validation errors in schema prop. I don't checked your updated schema problem. First, I'm waiting a fiddle from you. :)

**Comment by jmverges** [comment]
How can I create a fiddle for Vue?

**Comment by icebob** [comment]
Fork it: https://jsfiddle.net/icebob/0mg1v81e/
And modify the JS to demonstrate your issue.
"Update" and send me the link

**Comment by jmverges** [comment]
I don't get it running int fiddle but something like this https://jsfiddle.net/ym6dn8zd/1/

**Comment by icebob** [comment]
Now it's running, but what is the exact problem? https://jsfiddle.net/ym6dn8zd/4/

**Comment by jmverges** [comment]
https://jsfiddle.net/ym6dn8zd/7/ I cannot reproduce it in there, weird

**Comment by jmverges** [comment]
Forgot it, was my own problem, didn't see it

**Comment by icebob** [comment]
Published: https://github.com/icebob/vue-form-generator/releases/tag/v2.0.0-beta7

**Pull request merged**
