### PR TITLE
:bug: bug: "Invalid date" message in pikaday field.

### PR DESCRIPTION
**Pull request by lionel-bijaoui**
Change dev schema for a simple one. Delete default in pikaday field.
#59

### CODE REVIEW

**Comment by icebob** [comment]
Why solve it the problem?

**Comment by icebob** [comment]
I closed because it is not solved the problem.

**Comment by lionel-bijaoui** [comment]
I agree it does not solve the problem.
But can you remove line 52 to 84 of `fieldPikaday.vue` ? There is no need for this now that the doc is ready. We don't want to override the default of the plugin with the same option as the default of the plugin, it is pointless.

**Comment by icebob** [comment]
Merged

**Pull request merged**
