### PR TITLE
Better accessibility labels

### LINKED ISSUE #74: Better accessibility
Let's not forget about this, the web is for everybody.
I don't have experience with this, it could be nice to have someone who know about these stuff on board to help.
We could start with [labels](https://www.w3.org/WAI/tutorials/forms/labels/).

Documentation and information:
- https://www.w3.org/WAI/tutorials/forms/
- https://www.w3.org/standards/webdesign/accessibility

### PR DESCRIPTION
**Pull request by dflock**
Starts to fix #74:

* Associate each label with it's control, by making sure that each
  control has an id, and using the labels `for` attribute to bind
  to this.
* Don't output label elements for button controls

I tried to keep the change set minimal, but some trailing white-space got removed.

### CODE REVIEW

**Comment by icebob** [comment]
Thanks, I will check it. Could you fix eslint errors?

**Comment by dflock** [comment]
OK, eslint errors fixed, sorry about that - I normally use standard, so didn't run eslint :blush:

**Comment by icebob** [comment]
No problem, thanks for fixing :)

**Comment by dflock** [comment]
Just to be clear, this is merge-able, but not complete - not all inputs done and form level id prefix not done. Let me know what you think after testing and I'll update & complete.

**Comment by icebob** [comment]
I need more time, because I'm ill. :face_with_thermometer:

**Comment by dflock** [comment]
Hope you feel better soon!

In the meantime, I've pushed support for a few more input types.

**Comment by icebob** [comment]
Thanks!

Great commit!

**Comment by icebob** [comment]
@dflock I checked commits. My suggestion is that, abstractField has reference to the `schema` as `this.schema`. So not neccessary to pass as parameter to `getFieldID`. And if no params, it can be a computed field as `fieldID`. What do you think?

```js
	computed: {
		fieldID() {
			// Try to get a reasonable default id from the this.schema,
			// then slugify it.
			if (typeof this.schema.id !== "undefined") {
				// If an ID's been explicitly set, use it unchanged
				return this.schema.id;
			} else {
				return (this.schema.inputName || this.schema.label || this.schema.model)
				.toString()
				.trim()
				.toLowerCase()
				// Spaces to dashes
				.replace(/ /g, "-")
				// Multiple dashes to one
				.replace(/-{2,}/g, "-")
				// Remove leading & trailing dashes
				.replace(/^-+|-+$/g, "")
				// Remove anything that isn't a (English/ASCII) letter or number.
				.replace(/([^a-zA-Z0-9\._-]+)/g, "")
				;
			}
		}
	}
```

**Comment by dflock** [comment]
Sorry, I've been up to my eyeballs lately and haven't had a chance to finish this off. I found some time to try your suggestion and it seemed to work OK in the components and `abstractField.js`, but not in `formGenerator.vue`. I didn't get chance to figure out why yet; I think `this.schema` means something different there?

Anyway, I'll try to get back to this as soon as I can - I'd really like to get this merged at some point - I haven't forgotten about it!

**Comment by icebob** [comment]
Thanks. 
In this case, keep your `getFieldID` solution instead of my computed fields.

**Comment by dflock** [comment]
I'm back working on this again - sorry for the delay!

OK, I've pulled [this branch](https://github.com/phemisystems/vue-form-generator/tree/better-accessibility-labels) up to date with current master.

Can you re-open this pull request, or do you want me to start a new one?

**Comment by icebob** [comment]
Hi,

I can't reopen because base branch (next) is deleted. You need to fork from `master`

**Pull request closed without merging**
