### PR TITLE
rename dateTime to dateTimePicker and slider to rangeSlider

### PR DESCRIPTION
**Pull request by lionel-bijaoui**
#50 
I have also renamed sliderOptions to noUiSliderOptions to follow the logic used so far:
- `field[name]` 
- `[name]Options`

There was also a little mistake in the unit test of noUiSlider.

### CODE REVIEW

**Comment by lionel-bijaoui** [comment]
@icebob please, can you merge if this is ok ? I'm blocked by the PR to do the next.

**Comment by icebob** [comment]
Merged.

**Comment by lionel-bijaoui** [comment]
Thank you !

**Comment by icebob** [comment]
Me too :)

**Pull request merged**
