### PR TITLE
support async (promised) validators

### PR DESCRIPTION
**Pull request by icebob**
Handle async validator which returns with Promise. Discussion: #170 

Example async validators in dev:

```js
let customAsyncValidator = function(value) {
	return new Promise((resolve, reject) => {
		setTimeout(() => {
			if (value)
				resolve();
			else
				resolve([ "Invalid value from async validator" ]);
		}, 1000);
	});
};
```

Schema:
```js
{
	type: "input",
	inputType: "url",
	label: "URL",
	model: "website",
	validator: customAsyncValidator
}
```

TODO:
- [ ] add tests

### CODE REVIEW

**Comment by cristijora** [comment]
Nice. @jmverges take a look :)

**Comment by jmverges** [comment]
@icebob works properly for me, thank you!

**Comment by icebob** [comment]
Great! You're welcome.

**Comment by icebob** [comment]
Released in [v2.0.0-beta6](https://github.com/icebob/vue-form-generator/releases/tag/v2.0.0-beta6)

**Pull request merged**
