### PR TITLE
Feat/select get item name

### PR DESCRIPTION
**Pull request by sorodrigo**
This PR includes the `name` option in `selectOptions` of the select field. Copies the behaviour of the `name` option in `checklistOptions` of the checklist field.

### CODE REVIEW

**Comment by icebob** [comment]
Great! I will check.

**Comment by icebob** [comment]
Please copy the both (getItemName & getItemValue) logic from fieldChecklist. After it will be complete.

Btw, could you cover it with tests?

**Comment by sorodrigo** [comment]
Will do, thanks!

**Comment by icebob** [comment]
Implemented in https://github.com/icebob/vue-form-generator/commit/42b4fcb533282da446a72ccfc8b7bd7b7128b6e7

**Comment by sorodrigo** [comment]
Thanks! Sorry I never found time to update the PR. @icebob

**Pull request closed without merging**
