### PR TITLE
Vue2

### PR DESCRIPTION
**Pull request by sureshamk**
this branch will work with vue2

### CODE REVIEW

**Comment by lionel-bijaoui** [comment]
hi @sureshamk, I you taken a look at my PR #89 before doing that ? They have the same goal so maybe it could help ?
@icebob what should we do ? I'm perfectly fine with @sureshamk finishing the transfer to Vuejs2 since I'm very busy. This is a very a welcome help.
Whatever the decision, thank you for your help @sureshamk ! 😄

**Comment by icebob** [comment]
@lionel-bijaoui I checked @sureshamk commit, but I don't find any v2 relevant code, just formatting and syntax fixing. We need more work to release a new version, because we need test & fix every fields

**Comment by lionel-bijaoui** [comment]
@icebob well then, what should I do ? Continue to work on my branch and ignore this ?

**Comment by icebob** [comment]
Yes, keep work in your branch & PR.

**Pull request closed without merging**
