### PR TITLE
Better accessibility labels - to master

### PR DESCRIPTION
**Pull request by dflock**
Same as #105, but onto the master branch, instead of the old next branch.

### CODE REVIEW

**Comment by icebob** [comment]
@dflock Thank you. Nice PR! Could you add test for `abstractField.getFieldID` ?

**Comment by dflock** [comment]
Was trying to add a test to `vue-form-generator/test/unit/specs/VueFormGenerator.spec.js` to test the `fieldTypeHasLabel` function, but I couldn't figure out how to call that function from the test?

**Comment by dflock** [comment]
I should probably update the docs, too. How do I submit a pull request for [this](https://icebob.gitbooks.io/vueformgenerator/content/fields/field_properties.html)?

**Comment by icebob** [comment]
For `fieldTypeHasLabel` create a simple `describe` block:
```js
describe("check fieldTypeHasLabel function", () => {
	before( () => {
		createFormGenerator({ fields: [] }, {});
	});

	it("should return true", () => {
		expect(vm.fieldTypeHasLabel({ type: "input", inputType: "checkbox"})).to.be.true;
		expect(vm.fieldTypeHasLabel({ type: "input", inputType: "text"})).to.be.true;
	});	

	it("should return false", () => {
		expect(vm.fieldTypeHasLabel({ type: "input", inputType: "button"})).to.be.false;
		expect(vm.fieldTypeHasLabel({ type: "checklist" })).to.be.false;
	});	
});
```
> The code is just a sketch, not guaranteed it is working.

To update docs, you need to register on gitbook and send me your username.

**Comment by dflock** [comment]
That (and variants) are basically what I tried - but I couldn't figure out how to actually _call_ the `fieldTypeHasLabel` function _successfully_. If I copy your code and run the tests I get this:

```
check fieldTypeHasLabel function
  ✗ should return true
undefined is not a function (evaluating 'vm.fieldTypeHasLabel({ type: "input", inputType: "checkbox" })')
```
So maybe the `vm` object doesn't have a fieldTypeHasLabel` method at that point?

If I add a `console.log(vm)` in there, it prints out a load of this kind of stuff:

```
..., _vnode: ..., _staticTrees: ..., $slots: ..., $scopedSlots: ..., _c: ..., $createElement: ..., _watchers: ..., disabled: ..., schema: ..., model: ..., options: ..., multiple: ..., isNewModel: ..., tag: ..., validate: ..., clearValidationErrors: ..., setModelValueByPath: ..., getFieldID: ..., getFieldRowClasses: ..., getFieldType: ..., fieldTypeHasLabel: ..., fieldDisabled: ..., fieldRequired: ..., fieldVisible: ..., fieldReadonly: ..., fieldFeatured: ..., buttonClickHandler: ..., onFieldValidated: ..., modelUpdated: ..., buttonVisibility: ..., fieldErrors: ..., _data: ..., errors: ..., value: ..., fields: ..., $el: ...}], $refs: Object{form: VueComponent{_uid: ..., _isVue: ..., $options: ..., _renderProxy: ..., _self: ..., $parent: ..., $root: ..., $children: ..., $refs: ..., _watcher: ..., _inactive: ..., _isMoun
```

which _does_ include `, fieldTypeHasLabel: ` a couple of times. I've not written node/karma unit tests before, so I'm not sure the best way to debug what's going on in the tests?

I've added my code to the branch so you can try it out.

**Comment by dflock** [comment]
Also, my gitbooks username is `dflock`.

**Comment by icebob** [comment]
I was wrong becase `vm` is the parent and not the vfg instance.
Change the test to it:
```js
	describe("check fieldTypeHasLabel function", () => {
		let form;
		before( () => {
			createFormGenerator({ fields: [] }, {});
			form = vm.$refs.form;
		});

		it("should return true", () => {
			expect(form.fieldTypeHasLabel({ type: "input", inputType: "checkbox"})).to.be.true;
			expect(form.fieldTypeHasLabel({ type: "input", inputType: "text"})).to.be.true;
			expect(form.fieldTypeHasLabel({ type: "checklist" })).to.be.true;
		});

		it("should return false", () => {
			expect(form.fieldTypeHasLabel({ type: "input", inputType: "button"})).to.be.false;
			expect(form.fieldTypeHasLabel({ type: "input", inputType: "image"})).to.be.false;
			expect(form.fieldTypeHasLabel({ type: "input", inputType: "submit"})).to.be.false;
			expect(form.fieldTypeHasLabel({ type: "input", inputType: "reset"})).to.be.false;
		});
	});
```

**Comment by dflock** [comment]
Thanks! Test fixed and pushed. Will work on docs now.

**Comment by dflock** [comment]
OK, docs changes here: https://www.gitbook.com/book/icebob/vueformgenerator/changes/5

**Comment by icebob** [comment]
Thank you. Nice PR! Merged.

**Comment by icebob** [comment]
Published: https://github.com/icebob/vue-form-generator/releases/tag/v2.0.0-beta7

**Pull request merged**
