### PR TITLE
Update the options for the v2 of multiselect

### PR DESCRIPTION
**Pull request by lionel-bijaoui**
This is a WIP and I would like help to finish it.

see #239 for details and discussion

TODO:
- ~~find a solution for partials~~
- [x] update the test
- [ ] update the documentation

### CODE REVIEW

**Comment by icebob** [comment]
@lionel-bijaoui Is it blocking the stable v2 of vfg?

**Comment by lionel-bijaoui** [comment]
@icebob Yeah, sorry, It's still in progress.
I don't know if it is blocking. Do you have a release date for the v2?

**Comment by icebob** [comment]
OK. I would like release stable in the week.

**Comment by lionel-bijaoui** [comment]
Comment where not allowed in more than one place, hence the failure.
I just had to update one thing for the test to work.
@icebob if you validate, I will modify the doc.
The biggest change is that `multiple` is now under `selectOptions`.
I have checked [the doc](https://icebob.gitbooks.io/vueformgenerator/fields/field_properties.html) and except for `multi` there is no `multiple` option in the common properties of fields. This is why I moved it under `selectOptions`.

**Comment by icebob** [comment]
Thank you. Mergeable!

**Comment by lionel-bijaoui** [comment]
[Change made in the documentation](https://www.gitbook.com/book/icebob/vueformgenerator/changes/9).
I did another PR #242 for the missing option that I missed.

**Comment by icebob** [comment]
Thanks. Doc is merged.

**Pull request merged**
